version: 0.2
phases:
  pre_build:
    commands:
    - |
      if [ "$USE_MOCK" = "true" ]; then
        echo "use_mock is true: Starting NotifyPit..."
        echo "Phase 1: Creating Docker Network"
        docker network create smoke-test-net || echo "Network might already exist, continuing..."
        # VERIFICATION: If this fails, we know exactly where the issue is
        docker network inspect smoke-test-net > /dev/null || (echo "CRITICAL: Network smoke-test-net was NOT created!" && exit 1)
        echo "Phase 2: Pull from NotifyPit GIT Hub"
        git clone https://github.com/leonaAtkins/notify-pit.git notify-pit
        cd notify-pit
        make serve
        echo "Phase 3: Connecting Container to Network"
        CONTAINER_ID=$(docker ps -q --filter "label=com.docker.compose.service=notifypit")
        if [ -z "$CONTAINER_ID" ]; then
          echo "Error: NotifyPit container not found!"
          docker compose logs
          exit 1
        fi
        docker network connect smoke-test-net $CONTAINER_ID --alias notifypit
        echo "Phase 4: Waiting for NotifyPit to respond on notifypit:4567..."
        TIMEOUT=30
        echo "Container Health Check"
        while ! curl -s -f http://localhost:4567/health > /dev/null; do
          TIMEOUT=$((TIMEOUT-1))
          if [ $TIMEOUT -le 0 ]; then
            echo "Timed out waiting for NotifyPit!"
            docker compose logs
            exit 1
          fi
          printf '.'
          sleep 5
        done
        echo "Container-to-Container Check"
        # We run a tiny curl container on the SAME network the tests will use
        docker run --rm --network smoke-test-net curlimages/curl \
          curl -s -f --connect-timeout 5 http://notifypit:4567/health \
          || (echo "CRITICAL ERROR: Smoke test network cannot reach 'notifypit' alias!" && exit 1)
        echo "\n NotifyPit is up!"
        export NOTIFY_BASE_URL=http://notifypit:4567
        export DOCKER_NETWORK_MODE="--network smoke-test-net"
        export NOTIFY_GO_TEMPLATE_ID="go_template_id"
        echo "Running tests on govwifi-net against $NOTIFY_BASE_URL"
        cd ..
        echo "Phase 5: Running Tests"
      else
        echo "use_mock is false: Running tests against real Notify API..."
        export NOTIFY_BASE_URL="https://api.notifications.service.gov.uk"
        export DOCKER_NETWORK_MODE=""
      fi
    - echo "Setting up ECR image URI"
    - ECR_IMAGE_URI=$TOOLS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/govwifi/$ENVIRONMENT/$APP_NAME:latest
    - echo "Logging in to ECR"
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $TOOLS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    - echo "Setting up test environment variables"
    - export TEST_ENV_VARS="-e DOCKER=docker -e GW_SUPER_ADMIN_USER -e GW_SUPER_ADMIN_PASS -e GW_SUPER_ADMIN_2FA_SECRET -e GW_USER -e GW_PASS -e GW_2FA_SECRET -e GOOGLE_API_CREDENTIALS -e GOOGLE_API_TOKEN_DATA -e RADIUS_KEY -e RADIUS_IPS -e SUBDOMAIN -e NOTIFY_SMOKETEST_API_KEY -e NOTIFY_BASE_URL -e NOTIFY_GO_TEMPLATE_ID -e GOVWIFI_PHONE_NUMBER -e SMOKETEST_PHONE_NUMBER -e NOTIFY_FIELD -e EAP_TLS_CLIENT_CERT -e EAP_TLS_CLIENT_KEY -e ENVIRONMENT"
  build:
    commands:
    - echo "Pull image from ECR"
    - docker pull $ECR_IMAGE_URI
    - echo "Running smoke tests inside the Docker container"
    - docker run --rm $DOCKER_NETWORK_MODE $TEST_ENV_VARS $ECR_IMAGE_URI bundle exec rspec spec/system
  post_build:
    commands:
    - |
      echo "--- 📜 DUMPING NOTIFYPIT LOGS ---"
      # 1. Find the ID dynamically (just like we did in Phase 3)
      CONTAINER_ID=$(docker ps -q --filter "label=com.docker.compose.service=notifypit")

      if [ ! -z "$CONTAINER_ID" ]; then
        echo "Found Container ID: $CONTAINER_ID"
        docker logs $CONTAINER_ID
      else
        echo "⚠️ Could not find a running container for 'notifypit'"
        # List all containers just in case it crashed and disappeared
        docker ps -a
      fi
