version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo "AWS_REGION is $AWS_REGION "
      - STAGING_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/govwifi/$APP/staging
      - PRODUCTION_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/govwifi/$APP/production
      - echo "REPOSITORY_URI is $REPOSITORY_URI"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "$DOCKER_HUB_AUTHTOKEN_ENV" | docker login -u $(echo $DOCKER_HUB_USERNAME_ENV) --password-stdin
  build:
    commands:
      - docker pull $STAGING_REPOSITORY_URI:latest
      - docker tag $STAGING_REPOSITORY_URI:latest $PRODUCTION_REPOSITORY_URI:latest
      - docker push $PRODUCTION_REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Push completed on `date`
