version: 0.2

phases:
  pre-build:
    commands:
    - echo "Setting up environment"
    - export GW_USER=$GW_USER
    - export GW_PASS=$GW_PASS
    - export GW_SUPER_ADMIN_USER=$GW_SUPER_ADMIN_USER
    - export GW_SUPER_ADMIN_PASS=$GW_SUPER_ADMIN_PASS

  build:
    commands:
    - echo "Running smoke tests reset"
    - |
      aws ecs run-task --region $AWS_REGION --cluster $CLUSTER \
      --task-definition $TASK_DEF \
      --launch-type FARGATE \
      --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SECURITY_GROUPS],assignPublicIp='ENABLED'}" \
      --overrides '{"containerOverrides":[{"name":$CONTAINER_NAME, "command": ["bundle", "exec", "rake", $RAKE_TASK_NAME]}]}'
